# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db43a54054b38611bea2e3b6b28dfd38e6c61d41b3d6a64be78354f93383e51c9cfcd79e6d4966a00eb8283b7e087ad3a4e737fbbcce37e406c0fc1ddd3c738b

test:
  secret_key_base: f32352e78733201ca5d85de782a809d57a39d06c815d7e9bbb42538b67e47dd8a2229c838a223d1571beef683fae19a7295ddd674b3c2612f2a9cbceac3605fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
